#!/usr/bin/python3
"""
File Name: play

Authors: Drake Oswald

Description: This program interacts with the controller to initialize a
game for the user.
"""

from controller import game_controller

rounds = int(input("How many rounds do you want to play? "))
game_controller(rounds)